LIBTD-1335: Migrate Composition+Performance Work creation/update functionality to Hyrax 2.1.0
VTUL/compel pull request #1
Opened 2018-06-06 19:09 UTC by shabububu

This pull requests contains modifications that essentially reimplement the Composition and Performance Work creation/update functionality to Hyrax 2.1.0 from Hyrax 1.0.3.

Code/Functionality is being migrated from:
https://github.com/VTUL/binary-arts/tree/5b89406e1aa662c2d5e039b370ea5067dbe26ac5 

The bulk of the Composition and Performance functionality is there, but customized stylesheets are still missing and can be added in later with LIBTD-1341. For example, the Composition Composer and Performance Performer are still visible in the forms, but this will change once the stylesheets have been brought over.

2018-06-07 18:03 UTC, tingtingjh requested changes
1. Basic metadata fields are populated correctly for both Composition and Performance.
2. Composer and performer fields are correctly populated in composition and performance, respectively.
4. Tag authority list is populated correctly.
5. But the "location" metadata should be rendered as an input box instead of auto-complete field.

2018-06-07 20:44 UTC, shabububu commented
In Hyrax 1.0.3, the default `based_near` field was a plain input field.  It was changed to an auto-complete field using geonames sometime after. It makes sense to change it back to plain input for now. If it's something that's desirable in the future, we can revert this change.

2018-06-08 14:13 UTC, tingtingjh commented
Try to use the newly introduced "location" directly in case the based_near being used by Hyrax2 in some specific way? Just need to change some labelings and edit_fields and show pages.

2018-06-08 14:25 UTC, shabububu commented
I migrated over the `location` property from the Hyrax 1.0.3 version, and it does not appear to be used there either. After discussing more with Tingting, we've decided to just remove the location references for now. They can put back in at a later time. (Also, this may potentially be addressed again in the clean up of the form entries with issues LIBTD-1330 and LIBTD-1331.)

2018-06-08 14:52 UTC, tingtingjh commented
Based_near property doesn't seem to populated at the show page.

2018-06-08 15:07 UTC, shabububu commented
It's true that the based_near isn't being displayed. It feels like the binary-arts dev branch that we're migrating code from may be not quite clean. It is a dev branch after all. Going forward, we may change less of these sorts of things in favor of making additional tickets after the migration is completed.

2018-06-08 15:39 UTC, shabububu commented
Added one more fix (that could potentially be a Hyrax bug) to get the based_near labels to show correctly in the search results.

2018-06-08 15:47 UTC, tingtingjh approved these changes

2018-06-08 15:47 UTC, merged